services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\Mktools\:
        resource: '../Classes/*'

    DMK\Mktools\Command\MigrateTscobjPluginsCommand:
        tags:
            - name: 'console.command'
              command: 'mktools:migrate-tscobj-plugins'
              schedulable: true
    DMK\Mktools\Command\SlugCreatorCommand:
        tags:
            - name: 'console.command'
              command: 'mktools:slug-creator'
              schedulable: true
    DMK\Mktools\Command\MigrateRealurlAliasToSlugCommand:
        tags:
            - name: 'console.command'
              command: 'mktools:migrate-realurl-alias-to-slug'
              schedulable: true
    DMK\Mktools\Command\MigrateFormFinishersCommand:
        tags:
            - name: 'console.command'
              command: 'mktools:migrate-form-finishers'
              schedulable: true
    DMK\Mktools\Command\MigrateTcaFileGroupToFalCommand:
      tags:
        - name: 'console.command'
          command: 'mktools:migrate-tca-file-groups-to-fal'
          schedulable: true

    DMK\Mktools\ContentObject\UserContentObject:
      tags:
        - name: frontend.contentobject
          identifier: 'USER'

    DMK\Mktools\ContentObject\UserInternalContentObject:
      tags:
        - name: frontend.contentobject
          identifier: 'USER_INT'
